### ISSUE TITLE
Decoding problems with some jpeg files

### ISSUE THREAD

**Issue by squix78** [fredericplante/JPEGDecoder#1]
Hi Frederic

Here for completeness and documentation the issue I emailed you earlier. With some images I get ugly artefacts which in my opinion are not the usual jpeg compression artefacts, especially since I set compression quality to 10 (lossless). Attached the examples working and not working, original file and screenshot

Thank you very much!
[
![splashnotworking](https://cloud.githubusercontent.com/assets/716822/21572206/e407f72a-ced6-11e6-89d9-3e66cac190e2.jpg)
![splashworking](https://cloud.githubusercontent.com/assets/716822/21572205/e407dd30-ced6-11e6-8b61-bd49aa1c32ac.jpg)
![splashworkingscreenshot](https://cloud.githubusercontent.com/assets/716822/21572210/efe0b38e-ced6-11e6-981d-25deea29e002.JPG)
![splashnotworkingscreenshot](https://cloud.githubusercontent.com/assets/716822/21572211/efe0d7f6-ced6-11e6-9ead-fb961a2c40c8.JPG)
](url)

**Comment by fredericplante** [comment]
![baboon20](https://cloud.githubusercontent.com/assets/3188853/21572633/5e3ed898-cea9-11e6-9ddc-9875db9088cb.jpg)
 Try with this guy

**Comment by fredericplante** [comment]
Now, that is you original JPEG that I opened and saved using Paint.

![splash](https://cloud.githubusercontent.com/assets/3188853/21572754/d6041338-ceaa-11e6-9771-06398bd35827.jpg)

As you can see, it's about 3kB lighter then the original.

**Comment by fredericplante** [comment]
I still get some bugs out of the automation process, it's a work in progress, I expect it to become better with time, But still we are almost there, the picture is coming out.

**Comment by fredericplante** [comment]
![123016_1744 00](https://cloud.githubusercontent.com/assets/3188853/21573875/f60b7006-ceb7-11e6-9816-55e09c33a8e6.jpg)

A picture of your TFT showing in mine

**Comment by squix78** [comment]
I found the issue, maybe this will help you to fix it in the code or at least give a hint to users: When I re-encode the picture with sampling factor 2x2,1x1,1x1 then it works. I used this imagemagick command: 
convert SplashNotWorking.jpg -quality 100 -sampling-factor 2x2,1x1,1x1 SplashNotWorking-r.jpg 
before that command the picture had a sampling factor of 1x1,1x1,1x1 which caused the distortions

**Comment by fredericplante** [comment]
I got it fred straigt from an ov528 Jpeg
 It's Stiller running as we speaker, for ''testing'',  si I can wave passe it and des me à seconde later on the tft. Lol.

And way, I très alors of jpeg very few Mike à fussent. what to do with the verry few, Convert them usinG that old Winxp  computer during in you garage. Ses now you can justifier haine wifi in your garage, si ce it's your wifi Who did not Want that old dinosaure you call à cômputer, so you have to store it in the garage, or something.
