### ISSUE TITLE
Commits from 10 Jan - compilation error

### ISSUE THREAD

**Issue by reaper7** [fredericplante/JPEGDecoder#3]
After last update I can't compile any example and other projects. (on arduino 1.6.13 or 1.8.0).
I get:
```
C:\PROGRAMY\arduino_projekty\libraries\JPEGDecoder\examples\TFT_SPIFFS_jpg_v3\TFT_SPIFFS_jpg_v3.ino:36:25: fatal error: JPEGDecoder.h: No such file or directory

 #include <JPEGDecoder.h>

                         ^

compilation terminated.
```

New JPEGDecoder/exaples are not visible too inside arduino ide file->exaples,
but when I back to Your github version from 9 Jan, everything works

**Comment by fredericplante** [comment]
Yeah, it should be good now. Sorry about that

As for the fun_section. It wont appear in the Arduino example. But it will show in recent sketch list once you open it once

**Comment by reaper7** [comment]
now is ok
tnx!

**Comment by fredericplante** [comment]
I might move the fun section in the example folder, I'm going to take a look at the results in the Arduino IDE arborescence. My main worry is that it might make it heavier on the load process, or something.

JPEG is a large subject that include many kind of device, TV/VGA screen, TFT screen, Serial camera, Network and Storage device, I want this page to cover all interactions on this manner.

The main Idea, is to keep it concise and organised, and still be fun and understandable.

Any way, I want to thank you for your interest and quick error report, it's really appreciated. :) Cheer.
